import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/styles/globals.css";

import { redirect } from "next/navigation";

import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar";

import { cn } from "@/lib/utils";

import { auth } from "@/auth";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-screen antialiased",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <Navbar />
        <main className="container mx-auto h-[90vh]">{children}</main>
        <Toaster richColors={true} />
      </body>
    </html>
  );
}
